language: cpp
compiler: g++
os: linux
dist: bionic
before_install:
  - sudo apt-get install -y unzip zlib1g-dev libpng-dev libxpm-dev libx11-dev libxft-dev libxinerama-dev libfontconfig1-dev x11proto-xext-dev libxrender-dev libxfixes-dev
  - pushd lib
  - unzip fltk-1.3.5-mod.zip
  - cd fltk-1.3.5-mod
  - chmod +x configure
  - ./configure --prefix="$PWD/.." --with-abiversion=10305
  - make
  - make install
  - popd
script:
  - export PATH="$PWD/lib/bin:$PATH"
  - make
