name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt-get install -y git zlib1g-dev libpng-dev libxpm-dev libx11-dev libxft-dev libxinerama-dev libfontconfig1-dev x11proto-xext-dev libxrender-dev libxfixes-dev

      - name: Checkout FLTK
        uses: actions/checkout@master
        with:
          path: fltk
          repository: fltk/fltk
          ref: release-1.3.7
          fetch-depth: 1

      - name: Install FLTK
        working-directory: fltk
        run: |
          ./autogen.sh --prefix="$PWD/.." --with-abiversion=10307
          make
          make install

      - name: Build
        run: |
          export PATH="$PWD/bin:$PATH"
          make
